### ISSUE TITLE
harmonize newly added files

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/thun#3]
For the files listed, 
- remove key attribute for `<rs type="person"`
- add ref attribute including hash value and remove key attribute for `<rs type="place"`
- remove key attribute for `<rs type="org"`

See [this commit](https://github.com/acdh-oeaw/thun/commit/acc45040c924117c7b8cd8dba52756bfb58775a2) for a list of those files

**Comment by aureon249** [comment]
**DONE**
...e/thun/data/editions/alleruntertanigste-bemerkungen-thuns-zu-gymnasialreform-1857-a3-xxi-d439.xml
...n/data/editions/aufsatz-von-langenau-uber-einfluss-von-windischgraetz-1848-1849-12-a3-xxi-d23.xml
.../thun/data/editions/bemerkungen-thuns-zum-gesetz-uber-gymnasiallehramtsprufung-1849-a3-xxi-d4.xml
.../thun/data/editions/bemerkungen-zu-gesetzentwurf-ueber-kirchliche-gebaude-1854-05-a3-xxi-d261.xml
application-code/thun/data/editions/borovich-an-viale-prela-1856-01-03-a3-xxi-d363.xml
...tion-code/thun/data/editions/eingabe-der-oesterreichischen-buchhandler-1860-10-16-a3-xxi-d614.xml
application-code/thun/data/editions/entwurf-gesetz-verwaltung-kirchenguter-1860-a3-xxi-d642.xml
...ions/grundzuege-fur-organisierung-der-zivilverwaltung-lombardo-venetiens-1849-10-07-a3-xxi-d8.xml
application-code/thun/data/editions/gruss-aus-tirol-gedicht-fuer-leo-thun-1854-07-a3-xxi-d272.xml
...ation-code/thun/data/editions/gutachten-uber-volksschulen-von-krombholz-1850-05-31-a3-xxi-d54.xml
application-code/thun/data/editions/hahn-an-thun-1854-10-01-a3-xxi-d288.xml
application-code/thun/data/editions/konzept-thuns-uber-zustande-in-prag-1849-a3-xxi-d22.xml
application-code/thun/data/editions/linde-an-thun-1856-01-18-a3-xxi-d365.xml
application-code/thun/data/editions/lonyay-an-szogyeny-1860-04-17-a3-xxi-d573.xml
application-code/thun/data/editions/szantofy-uber-verlobung-von-jankovics-1857-12-28-a3-xxi-d438.xml
application-code/thun/data/editions/thun-an-celakovsky-1850-11-16-ca1058.xml
application-code/thun/data/editions/thun-an-rauscher-1853-04-02-ca826.xml
application-code/thun/data/editions/thun-an-rechberg-1857-07-21-ca1571.xml
application-code/thun/data/editions/thun-an-rechberg-1858-02-08-ca1572.xml

**Comment by csae8092** [comment]
make sure every @ref value starts with '#'

**Comment by csae8092** [comment]
done with https://github.com/acdh-oeaw/thun/blob/master/application-code/thun/process/addHashToRef.xsl
