### ISSUE TITLE
create meaningful listorg.xml

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/thun#4]
1. open file in `application-code\thun\data\editions` matching the first entry in `files_with_teiorg.xml` not marked with `<done>`
2.  search for `<orgName`
3.  substitute tag `<orgName>` with TEI code & corresponding organisation number from `application-code\thun\data\indices\listorg.xml` (e.g. `<rs type="org" ref="#org_0005">`)
4.  add organisation to `application-code\thun\data\indices\listorg.xml` in case it is not listed yet
5.  mark entry in `files_with_teiorg.xml` as done

**Comment by aureon249** [comment]
Abschluss-ToDos:
- als `orgname` fehlannotierte (?) Begriffe durchgehen: Celakovsky
- unklare Begriffe durchgehen: militärische Anstalt, Missionsgesellschaft
- URLs + Jahreszahlen der Organisationen durchgehen
- aus den `alt`-Titeln einen aussuchen
